<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MaritalStatus_dropdown</name>
   <tag></tag>
   <elementGuidId>68e127b4-b3ae-4eac-b6e3-2535cb987a74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>((//div[@class='oxd-form-row'])[3]/div/div[2]/div/div/div/div/div)[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
